config/routes.rb
Rails.application.routes.draw do
  resources :languages
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/language.rb
class Language < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :set_language, only: %i[ show edit update destroy ]

  # GET /languages or /languages.json
  def index
    @languages = Language.all
  end

  # GET /languages/1 or /languages/1.json
  def show
  end

  # GET /languages/new
  def new
    @language = Language.new
  end

  # GET /languages/1/edit
  def edit
  end

  # POST /languages or /languages.json
  def create
    @language = Language.new(language_params)

    respond_to do |format|
      if @language.save
        format.html { redirect_to language_url(@language), notice: "Language was successfully created." }
        format.json { render :show, status: :created, location: @language }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /languages/1 or /languages/1.json
  def update
    respond_to do |format|
      if @language.update(language_params)
        format.html { redirect_to language_url(@language), notice: "Language was successfully updated." }
        format.json { render :show, status: :ok, location: @language }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/1 or /languages/1.json
  def destroy
    @language.destroy

    respond_to do |format|
      format.html { redirect_to languages_url, notice: "Language was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_language
      @language = Language.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def language_params
      params.require(:language).permit(:title, :description, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/languages/_form.html.erb
<%= form_with(model: language) do |form| %>
  <% if language.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(language.errors.count, "error") %> prohibited this language from being saved:</h2>

      <ul>
        <% language.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_field :link %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/languages/_language.html.erb
<div id="<%= dom_id language %>">
  <p>
    <strong>Title:</strong>
    <%= language.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= language.description %>
  </p>

  <p>
    <strong>Link:</strong>
    <%= language.link %>
  </p>

</div>

app/views/languages/edit.html.erb
<h1>Editing language</h1>

<%= render "form", language: @language %>

<br>

<div>
  <%= link_to "Show this language", @language %> |
  <%= link_to "Back to languages", languages_path %>
</div>

app/views/languages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Languages</h1>

<div id="languages">
  <% @languages.each do |language| %>
    <%= render language %>
    <p>
      <%= link_to "Show this language", language %>
    </p>
  <% end %>
</div>

<%= link_to "New language", new_language_path %>

app/views/languages/new.html.erb
<h1>New language</h1>

<%= render "form", language: @language %>

<br>

<div>
  <%= link_to "Back to languages", languages_path %>
</div>

app/views/languages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @language %>

<div>
  <%= link_to "Edit this language", edit_language_path(@language) %> |
  <%= link_to "Back to languages", languages_path %>

  <%= button_to "Destroy this language", @language, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Languages</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>